### ISSUE TITLE
Addon possibly interfering with ElvUI

### ISSUE THREAD

**Issue by staplerx300** [fjaros/IgnoreLevel-2.4.3#2]
https://i.imgur.com/w22o4gS.jpg
https://i.imgur.com/E7sCujS.png
https://i.imgur.com/G39vrYl.png

Even reloaded the UI reinstalled ElvUI and it doesn't help. Is the addon tagging whispers as some other type of chat message or something?

**Comment by crborga** [comment]
Using WIM seems to interfere with this addon as well.

**Comment by fjaros** [comment]
Thanks for your reports guys. I'll work on a fix asap.

**Comment by fjaros** [comment]
Should be fixed guys. Download the new version. Make sure in addons delete old "IgnoreLevel" folder and just use the new "!IgnoreLevel" one.

**Comment by fjaros** [comment]
Found an issue with this - reopening

**Comment by staplerx300** [comment]
yeah it was working initially as far as the whispers window/double whispers bug, but now i'm still getting whispers from characters below the level set by my setting

**Comment by fjaros** [comment]
yep. i'm still iterating on a better solution. ElvUI is a pain in the ass for compatibility unfortunately.

**Comment by crborga** [comment]
Thank you for your efforts.

⁣Sent from BlueMail ​

**Comment by fjaros** [comment]
Please try the new version and let me know!

**Comment by staplerx300** [comment]
yeah it works great now @fjaros 

:)

**Comment by T0mken** [comment]
Got this problem after last update...

https://www.dropbox.com/s/ei2hlstjobuqkr1/double%20whisp.JPG?dl=0
https://www.dropbox.com/s/9l1nuk9my3qnr55/elvui%20ignorelevel.txt?dl=0
